#!/bin/sh
# rez-env redshift anima maya -- mayapy -m pytest tests/dcc/maya/test_asset_migration_tool.py::test_get_intermediate_tasks
rez-env redshift anima maya -- mayapy -m pytest -n auto tests/dcc/maya/test_asset_migration_tool.py
