# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eoyilmaz\Documents\development\anima\anima\anima\ui\ui_files\project_dialog.ui'
#
# Created: Mon May 08 19:08:56 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 545)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialog_label = QtWidgets.QLabel(Dialog)
        self.dialog_label.setStyleSheet("color: rgb(71, 143, 202);\n"
"font: 18pt;")
        self.dialog_label.setObjectName("dialog_label")
        self.verticalLayout.addWidget(self.dialog_label)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.project_info_formLayout = QtWidgets.QFormLayout()
        self.project_info_formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.project_info_formLayout.setObjectName("project_info_formLayout")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setObjectName("name_label")
        self.project_info_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_fields_verticalLayout = QtWidgets.QVBoxLayout()
        self.name_fields_verticalLayout.setObjectName("name_fields_verticalLayout")
        self.name_validator_label = QtWidgets.QLabel(Dialog)
        self.name_validator_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.name_validator_label.setObjectName("name_validator_label")
        self.name_fields_verticalLayout.addWidget(self.name_validator_label)
        self.project_info_formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.name_fields_verticalLayout)
        self.code_label = QtWidgets.QLabel(Dialog)
        self.code_label.setObjectName("code_label")
        self.project_info_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.code_label)
        self.code_fields_verticalLayout = QtWidgets.QVBoxLayout()
        self.code_fields_verticalLayout.setObjectName("code_fields_verticalLayout")
        self.code_validator_label = QtWidgets.QLabel(Dialog)
        self.code_validator_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.code_validator_label.setObjectName("code_validator_label")
        self.code_fields_verticalLayout.addWidget(self.code_validator_label)
        self.project_info_formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.code_fields_verticalLayout)
        self.type_label = QtWidgets.QLabel(Dialog)
        self.type_label.setObjectName("type_label")
        self.project_info_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.type_label)
        self.type_comboBox = QtWidgets.QComboBox(Dialog)
        self.type_comboBox.setEditable(True)
        self.type_comboBox.setObjectName("type_comboBox")
        self.project_info_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.type_comboBox)
        self.date_label = QtWidgets.QLabel(Dialog)
        self.date_label.setObjectName("date_label")
        self.project_info_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.date_label)
        self.date_dateEdit = QtWidgets.QDateEdit(Dialog)
        self.date_dateEdit.setObjectName("date_dateEdit")
        self.project_info_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.date_dateEdit)
        self.image_format_label = QtWidgets.QLabel(Dialog)
        self.image_format_label.setObjectName("image_format_label")
        self.project_info_formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.image_format_label)
        self.image_format_horizontalLayout = QtWidgets.QHBoxLayout()
        self.image_format_horizontalLayout.setObjectName("image_format_horizontalLayout")
        self.image_format_comboBox = QtWidgets.QComboBox(Dialog)
        self.image_format_comboBox.setObjectName("image_format_comboBox")
        self.image_format_horizontalLayout.addWidget(self.image_format_comboBox)
        self.update_image_format_pushButton = QtWidgets.QPushButton(Dialog)
        self.update_image_format_pushButton.setObjectName("update_image_format_pushButton")
        self.image_format_horizontalLayout.addWidget(self.update_image_format_pushButton)
        self.create_image_format_pushButton = QtWidgets.QPushButton(Dialog)
        self.create_image_format_pushButton.setObjectName("create_image_format_pushButton")
        self.image_format_horizontalLayout.addWidget(self.create_image_format_pushButton)
        self.image_format_horizontalLayout.setStretch(0, 1)
        self.project_info_formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.image_format_horizontalLayout)
        self.fps_label = QtWidgets.QLabel(Dialog)
        self.fps_label.setObjectName("fps_label")
        self.project_info_formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.fps_label)
        self.fps_spinBox = QtWidgets.QSpinBox(Dialog)
        self.fps_spinBox.setMinimum(1)
        self.fps_spinBox.setProperty("value", 25)
        self.fps_spinBox.setObjectName("fps_spinBox")
        self.project_info_formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fps_spinBox)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.project_info_formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.repository_horizontalLayout = QtWidgets.QHBoxLayout()
        self.repository_horizontalLayout.setObjectName("repository_horizontalLayout")
        self.repository_comboBox = QtWidgets.QComboBox(Dialog)
        self.repository_comboBox.setObjectName("repository_comboBox")
        self.repository_horizontalLayout.addWidget(self.repository_comboBox)
        self.update_repository_pushButton = QtWidgets.QPushButton(Dialog)
        self.update_repository_pushButton.setObjectName("update_repository_pushButton")
        self.repository_horizontalLayout.addWidget(self.update_repository_pushButton)
        self.create_repository_pushButton = QtWidgets.QPushButton(Dialog)
        self.create_repository_pushButton.setObjectName("create_repository_pushButton")
        self.repository_horizontalLayout.addWidget(self.create_repository_pushButton)
        self.repository_horizontalLayout.setStretch(0, 1)
        self.project_info_formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.repository_horizontalLayout)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.project_info_formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.structure_horizontalLayout = QtWidgets.QHBoxLayout()
        self.structure_horizontalLayout.setObjectName("structure_horizontalLayout")
        self.structure_comboBox = QtWidgets.QComboBox(Dialog)
        self.structure_comboBox.setObjectName("structure_comboBox")
        self.structure_horizontalLayout.addWidget(self.structure_comboBox)
        self.update_structure_pushButton = QtWidgets.QPushButton(Dialog)
        self.update_structure_pushButton.setObjectName("update_structure_pushButton")
        self.structure_horizontalLayout.addWidget(self.update_structure_pushButton)
        self.create_structure_pushButton = QtWidgets.QPushButton(Dialog)
        self.create_structure_pushButton.setObjectName("create_structure_pushButton")
        self.structure_horizontalLayout.addWidget(self.create_structure_pushButton)
        self.structure_horizontalLayout.setStretch(0, 1)
        self.project_info_formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.structure_horizontalLayout)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.project_info_formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.status_comboBox = QtWidgets.QComboBox(Dialog)
        self.status_comboBox.setObjectName("status_comboBox")
        self.project_info_formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.status_comboBox)
        self.verticalLayout.addLayout(self.project_info_formLayout)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("color: rgb(71, 143, 202);\n"
"font: 18pt;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.client_info_formLayout = QtWidgets.QFormLayout()
        self.client_info_formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.client_info_formLayout.setObjectName("client_info_formLayout")
        self.client_label = QtWidgets.QLabel(Dialog)
        self.client_label.setObjectName("client_label")
        self.client_info_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.client_label)
        self.client_comboBox = QtWidgets.QComboBox(Dialog)
        self.client_comboBox.setEditable(True)
        self.client_comboBox.setObjectName("client_comboBox")
        self.client_info_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.client_comboBox)
        self.agency_label = QtWidgets.QLabel(Dialog)
        self.agency_label.setObjectName("agency_label")
        self.client_info_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.agency_label)
        self.agency_comboBox = QtWidgets.QComboBox(Dialog)
        self.agency_comboBox.setEditable(True)
        self.agency_comboBox.setObjectName("agency_comboBox")
        self.client_info_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.agency_comboBox)
        self.production_company_label = QtWidgets.QLabel(Dialog)
        self.production_company_label.setObjectName("production_company_label")
        self.client_info_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.production_company_label)
        self.production_company_comboBox = QtWidgets.QComboBox(Dialog)
        self.production_company_comboBox.setEditable(True)
        self.production_company_comboBox.setObjectName("production_company_comboBox")
        self.client_info_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.production_company_comboBox)
        self.verticalLayout.addLayout(self.client_info_formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(5, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Project Dialog", None, -1))
        self.dialog_label.setText(QtWidgets.QApplication.translate("Dialog", "Create Project", None, -1))
        self.name_label.setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.name_validator_label.setText(QtWidgets.QApplication.translate("Dialog", "Validator Message", None, -1))
        self.code_label.setText(QtWidgets.QApplication.translate("Dialog", "Code", None, -1))
        self.code_validator_label.setText(QtWidgets.QApplication.translate("Dialog", "Validator Message", None, -1))
        self.type_label.setText(QtWidgets.QApplication.translate("Dialog", "Type", None, -1))
        self.date_label.setText(QtWidgets.QApplication.translate("Dialog", "Date", None, -1))
        self.image_format_label.setText(QtWidgets.QApplication.translate("Dialog", "Image Format", None, -1))
        self.update_image_format_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Update...", None, -1))
        self.create_image_format_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "New...", None, -1))
        self.fps_label.setText(QtWidgets.QApplication.translate("Dialog", "FPS", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Repository", None, -1))
        self.update_repository_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Update...", None, -1))
        self.create_repository_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "New...", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Structure", None, -1))
        self.update_structure_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Update...", None, -1))
        self.create_structure_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "New...", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Status", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Client Info", None, -1))
        self.client_label.setText(QtWidgets.QApplication.translate("Dialog", "Client", None, -1))
        self.agency_label.setText(QtWidgets.QApplication.translate("Dialog", "Agency", None, -1))
        self.production_company_label.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p align=\"right\">Production<br/>Company</p></body></html>", None, -1))

