# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eoyilmaz\Documents\development\anima\anima\anima\ui\ui_files\task_dialog.ui'
#
# Created: Tue May 02 09:18:36 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(462, 724)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.entity_type_comboBox = QtWidgets.QComboBox(Dialog)
        self.entity_type_comboBox.setObjectName("entity_type_comboBox")
        self.entity_type_comboBox.addItem("")
        self.entity_type_comboBox.addItem("")
        self.entity_type_comboBox.addItem("")
        self.entity_type_comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.entity_type_comboBox)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.projects_comboBox = QtWidgets.QComboBox(Dialog)
        self.projects_comboBox.setObjectName("projects_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.projects_comboBox)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parent_task_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.parent_task_lineEdit.setEnabled(False)
        self.parent_task_lineEdit.setObjectName("parent_task_lineEdit")
        self.horizontalLayout.addWidget(self.parent_task_lineEdit)
        self.pick_task_pushButton = QtWidgets.QPushButton(Dialog)
        self.pick_task_pushButton.setObjectName("pick_task_pushButton")
        self.horizontalLayout.addWidget(self.pick_task_pushButton)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.name_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.code_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.code_lineEdit.setObjectName("code_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.code_lineEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.task_type_comboBox = QtWidgets.QComboBox(Dialog)
        self.task_type_comboBox.setEditable(True)
        self.task_type_comboBox.setObjectName("task_type_comboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.task_type_comboBox)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.depends_listView = QtWidgets.QListView(Dialog)
        self.depends_listView.setObjectName("depends_listView")
        self.horizontalLayout_3.addWidget(self.depends_listView)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resources_listView = QtWidgets.QListView(Dialog)
        self.resources_listView.setObjectName("resources_listView")
        self.verticalLayout_2.addWidget(self.resources_listView)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setObjectName("listView")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.listView)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setObjectName("comboBox_7")
        self.horizontalLayout_2.addWidget(self.comboBox_7)
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_2.addWidget(self.comboBox_6)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setProperty("value", 500)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.projects_comboBox, self.name_lineEdit)
        Dialog.setTabOrder(self.name_lineEdit, self.task_type_comboBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Entity Type", None, -1))
        self.entity_type_comboBox.setItemText(0, QtWidgets.QApplication.translate("Dialog", "Task", None, -1))
        self.entity_type_comboBox.setItemText(1, QtWidgets.QApplication.translate("Dialog", "Asset", None, -1))
        self.entity_type_comboBox.setItemText(2, QtWidgets.QApplication.translate("Dialog", "Shot", None, -1))
        self.entity_type_comboBox.setItemText(3, QtWidgets.QApplication.translate("Dialog", "Sequence", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Project", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Parent", None, -1))
        self.pick_task_pushButton.setToolTip(QtWidgets.QApplication.translate("Dialog", "Pick parent task", None, -1))
        self.pick_task_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "Code", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Task Type", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "Depends To", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Resources", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "Responsible", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "Schedule Timing", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Priority", None, -1))

