# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eoyilmaz\Documents\development\anima\anima\ui\ui_files\time_log_dialog.ui'
#
# Created: Fri Feb 10 02:19:26 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 546)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.tasks_label = QtWidgets.QLabel(Dialog)
        self.tasks_label.setObjectName("tasks_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tasks_label)
        self.task_progressBar = QtWidgets.QProgressBar(Dialog)
        self.task_progressBar.setProperty("value", 24)
        self.task_progressBar.setObjectName("task_progressBar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.task_progressBar)
        self.resources_label = QtWidgets.QLabel(Dialog)
        self.resources_label.setObjectName("resources_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.resources_label)
        self.resource_comboBox = QtWidgets.QComboBox(Dialog)
        self.resource_comboBox.setObjectName("resource_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.resource_comboBox)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setObjectName("calendarWidget")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.calendarWidget)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.info_area_label = QtWidgets.QLabel(Dialog)
        self.info_area_label.setObjectName("info_area_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.info_area_label)
        self.revision_label = QtWidgets.QLabel(Dialog)
        self.revision_label.setObjectName("revision_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.revision_label)
        self.revision_type_comboBox = QtWidgets.QComboBox(Dialog)
        self.revision_type_comboBox.setObjectName("revision_type_comboBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.revision_type_comboBox)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.description_plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.description_plainTextEdit.setObjectName("description_plainTextEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.description_plainTextEdit)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.not_finished_yet_radioButton = QtWidgets.QRadioButton(Dialog)
        self.not_finished_yet_radioButton.setChecked(True)
        self.not_finished_yet_radioButton.setObjectName("not_finished_yet_radioButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.not_finished_yet_radioButton)
        self.set_as_complete_radioButton = QtWidgets.QRadioButton(Dialog)
        self.set_as_complete_radioButton.setObjectName("set_as_complete_radioButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.set_as_complete_radioButton)
        self.submit_for_final_review_radioButton = QtWidgets.QRadioButton(Dialog)
        self.submit_for_final_review_radioButton.setObjectName("submit_for_final_review_radioButton")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.submit_for_final_review_radioButton)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.tasks_label.setText(QtWidgets.QApplication.translate("Dialog", "Task", None, -1))
        self.resources_label.setText(QtWidgets.QApplication.translate("Dialog", "Resource", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Date", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Start", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "End", None, -1))
        self.info_area_label.setText(QtWidgets.QApplication.translate("Dialog", "INFO", None, -1))
        self.revision_label.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p align=\"right\">Revision<br/>Type</p></body></html>", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Description", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "Status", None, -1))
        self.not_finished_yet_radioButton.setText(QtWidgets.QApplication.translate("Dialog", "Not Finished Yet", None, -1))
        self.set_as_complete_radioButton.setText(QtWidgets.QApplication.translate("Dialog", "Set As Complete", None, -1))
        self.submit_for_final_review_radioButton.setText(QtWidgets.QApplication.translate("Dialog", "Submit For Final Review", None, -1))

