# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eoyilmaz\Documents\development\anima\anima\anima\ui\ui_files\version_creator.ui'
#
# Created: Thu May 04 10:10:16 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(1753, 769)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.logged_in_as_label = QtWidgets.QLabel(self.verticalWidget)
        self.logged_in_as_label.setTextFormat(QtCore.Qt.AutoText)
        self.logged_in_as_label.setObjectName("logged_in_as_label")
        self.horizontalLayout_11.addWidget(self.logged_in_as_label)
        self.logged_in_user_label = QtWidgets.QLabel(self.verticalWidget)
        self.logged_in_user_label.setObjectName("logged_in_user_label")
        self.horizontalLayout_11.addWidget(self.logged_in_user_label)
        self.logout_pushButton = QtWidgets.QPushButton(self.verticalWidget)
        self.logout_pushButton.setObjectName("logout_pushButton")
        self.horizontalLayout_11.addWidget(self.logout_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.line_3 = QtWidgets.QFrame(self.verticalWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tasks_groupBox = QtWidgets.QGroupBox(self.verticalWidget)
        self.tasks_groupBox.setObjectName("tasks_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tasks_groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.my_tasks_only_checkBox = QtWidgets.QCheckBox(self.tasks_groupBox)
        self.my_tasks_only_checkBox.setChecked(False)
        self.my_tasks_only_checkBox.setObjectName("my_tasks_only_checkBox")
        self.verticalLayout_2.addWidget(self.my_tasks_only_checkBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_task_lineEdit = QtWidgets.QLineEdit(self.tasks_groupBox)
        self.search_task_lineEdit.setObjectName("search_task_lineEdit")
        self.horizontalLayout_4.addWidget(self.search_task_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tasks_treeView = QtWidgets.QTreeView(self.tasks_groupBox)
        self.tasks_treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tasks_treeView.setAlternatingRowColors(True)
        self.tasks_treeView.setUniformRowHeights(True)
        self.tasks_treeView.setObjectName("tasks_treeView")
        self.tasks_treeView.header().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.tasks_treeView)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.recent_files_comboBox = QtWidgets.QComboBox(self.tasks_groupBox)
        self.recent_files_comboBox.setObjectName("recent_files_comboBox")
        self.horizontalLayout_8.addWidget(self.recent_files_comboBox)
        self.clear_recent_files_pushButton = QtWidgets.QPushButton(self.tasks_groupBox)
        self.clear_recent_files_pushButton.setObjectName("clear_recent_files_pushButton")
        self.horizontalLayout_8.addWidget(self.clear_recent_files_pushButton)
        self.horizontalLayout_8.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.find_from_path_lineEdit = QtWidgets.QLineEdit(self.tasks_groupBox)
        self.find_from_path_lineEdit.setObjectName("find_from_path_lineEdit")
        self.horizontalLayout_3.addWidget(self.find_from_path_lineEdit)
        self.find_from_path_pushButton = QtWidgets.QPushButton(self.tasks_groupBox)
        self.find_from_path_pushButton.setDefault(True)
        self.find_from_path_pushButton.setObjectName("find_from_path_pushButton")
        self.horizontalLayout_3.addWidget(self.find_from_path_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.thumbnail_graphicsView = QtWidgets.QGraphicsView(self.tasks_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnail_graphicsView.sizePolicy().hasHeightForWidth())
        self.thumbnail_graphicsView.setSizePolicy(sizePolicy)
        self.thumbnail_graphicsView.setMinimumSize(QtCore.QSize(320, 180))
        self.thumbnail_graphicsView.setMaximumSize(QtCore.QSize(320, 180))
        self.thumbnail_graphicsView.setAutoFillBackground(False)
        self.thumbnail_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.thumbnail_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.thumbnail_graphicsView.setBackgroundBrush(brush)
        self.thumbnail_graphicsView.setInteractive(False)
        self.thumbnail_graphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.thumbnail_graphicsView.setObjectName("thumbnail_graphicsView")
        self.verticalLayout_2.addWidget(self.thumbnail_graphicsView)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.upload_thumbnail_pushButton = QtWidgets.QPushButton(self.tasks_groupBox)
        self.upload_thumbnail_pushButton.setObjectName("upload_thumbnail_pushButton")
        self.horizontalLayout_16.addWidget(self.upload_thumbnail_pushButton)
        self.clear_thumbnail_pushButton = QtWidgets.QPushButton(self.tasks_groupBox)
        self.clear_thumbnail_pushButton.setObjectName("clear_thumbnail_pushButton")
        self.horizontalLayout_16.addWidget(self.clear_thumbnail_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14.addWidget(self.tasks_groupBox)
        self.new_version_groupBox = QtWidgets.QGroupBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.new_version_groupBox.setFont(font)
        self.new_version_groupBox.setObjectName("new_version_groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.new_version_groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.takes_label = QtWidgets.QLabel(self.new_version_groupBox)
        self.takes_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.takes_label.setFont(font)
        self.takes_label.setObjectName("takes_label")
        self.horizontalLayout_9.addWidget(self.takes_label)
        self.repr_as_separate_takes_checkBox = QtWidgets.QCheckBox(self.new_version_groupBox)
        self.repr_as_separate_takes_checkBox.setObjectName("repr_as_separate_takes_checkBox")
        self.horizontalLayout_9.addWidget(self.repr_as_separate_takes_checkBox)
        self.add_take_pushButton = QtWidgets.QPushButton(self.new_version_groupBox)
        self.add_take_pushButton.setObjectName("add_take_pushButton")
        self.horizontalLayout_9.addWidget(self.add_take_pushButton)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.takes_listWidget = QtWidgets.QListWidget(self.new_version_groupBox)
        self.takes_listWidget.setObjectName("takes_listWidget")
        self.horizontalLayout_6.addWidget(self.takes_listWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.description_label = QtWidgets.QLabel(self.new_version_groupBox)
        self.description_label.setMinimumSize(QtCore.QSize(35, 0))
        self.description_label.setObjectName("description_label")
        self.verticalLayout_3.addWidget(self.description_label)
        self.description_textEdit = QtWidgets.QTextEdit(self.new_version_groupBox)
        self.description_textEdit.setEnabled(True)
        self.description_textEdit.setTabChangesFocus(True)
        self.description_textEdit.setObjectName("description_textEdit")
        self.verticalLayout_3.addWidget(self.description_textEdit)
        self.verticalLayout_3.setStretch(1, 10)
        self.verticalLayout_3.setStretch(3, 3)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.environment_comboBox = QtWidgets.QComboBox(self.new_version_groupBox)
        self.environment_comboBox.setObjectName("environment_comboBox")
        self.horizontalLayout_2.addWidget(self.environment_comboBox)
        self.export_as_pushButton = QtWidgets.QPushButton(self.new_version_groupBox)
        self.export_as_pushButton.setObjectName("export_as_pushButton")
        self.horizontalLayout_2.addWidget(self.export_as_pushButton)
        self.save_as_pushButton = QtWidgets.QPushButton(self.new_version_groupBox)
        self.save_as_pushButton.setDefault(False)
        self.save_as_pushButton.setObjectName("save_as_pushButton")
        self.horizontalLayout_2.addWidget(self.save_as_pushButton)
        self.publish_pushButton = QtWidgets.QPushButton(self.new_version_groupBox)
        self.publish_pushButton.setObjectName("publish_pushButton")
        self.horizontalLayout_2.addWidget(self.publish_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_14.addWidget(self.new_version_groupBox)
        self.previous_versions_groupBox = QtWidgets.QGroupBox(self.verticalWidget)
        self.previous_versions_groupBox.setObjectName("previous_versions_groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.previous_versions_groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.show_only_label = QtWidgets.QLabel(self.previous_versions_groupBox)
        self.show_only_label.setObjectName("show_only_label")
        self.horizontalLayout_10.addWidget(self.show_only_label)
        self.version_count_spinBox = QtWidgets.QSpinBox(self.previous_versions_groupBox)
        self.version_count_spinBox.setMaximum(999999)
        self.version_count_spinBox.setProperty("value", 25)
        self.version_count_spinBox.setObjectName("version_count_spinBox")
        self.horizontalLayout_10.addWidget(self.version_count_spinBox)
        self.line = QtWidgets.QFrame(self.previous_versions_groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_10.addWidget(self.line)
        self.show_published_only_checkBox = QtWidgets.QCheckBox(self.previous_versions_groupBox)
        self.show_published_only_checkBox.setObjectName("show_published_only_checkBox")
        self.horizontalLayout_10.addWidget(self.show_published_only_checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.previous_versions_tableWidget = QtWidgets.QTableWidget(self.previous_versions_groupBox)
        self.previous_versions_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.previous_versions_tableWidget.setAlternatingRowColors(True)
        self.previous_versions_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.previous_versions_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.previous_versions_tableWidget.setShowGrid(False)
        self.previous_versions_tableWidget.setColumnCount(5)
        self.previous_versions_tableWidget.setObjectName("previous_versions_tableWidget")
        self.previous_versions_tableWidget.setColumnCount(5)
        self.previous_versions_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.previous_versions_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.previous_versions_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.previous_versions_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.previous_versions_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.previous_versions_tableWidget.setHorizontalHeaderItem(4, item)
        self.previous_versions_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.previous_versions_tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.previous_versions_tableWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.previous_versions_groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.representations_comboBox = QtWidgets.QComboBox(self.previous_versions_groupBox)
        self.representations_comboBox.setObjectName("representations_comboBox")
        self.horizontalLayout_5.addWidget(self.representations_comboBox)
        self.label_2 = QtWidgets.QLabel(self.previous_versions_groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.ref_depth_comboBox = QtWidgets.QComboBox(self.previous_versions_groupBox)
        self.ref_depth_comboBox.setObjectName("ref_depth_comboBox")
        self.horizontalLayout_5.addWidget(self.ref_depth_comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.useNameSpace_checkBox = QtWidgets.QCheckBox(self.previous_versions_groupBox)
        self.useNameSpace_checkBox.setChecked(True)
        self.useNameSpace_checkBox.setObjectName("useNameSpace_checkBox")
        self.horizontalLayout_5.addWidget(self.useNameSpace_checkBox)
        self.chose_pushButton = QtWidgets.QPushButton(self.previous_versions_groupBox)
        self.chose_pushButton.setObjectName("chose_pushButton")
        self.horizontalLayout_5.addWidget(self.chose_pushButton)
        self.checkUpdates_checkBox = QtWidgets.QCheckBox(self.previous_versions_groupBox)
        self.checkUpdates_checkBox.setChecked(True)
        self.checkUpdates_checkBox.setObjectName("checkUpdates_checkBox")
        self.horizontalLayout_5.addWidget(self.checkUpdates_checkBox)
        self.open_pushButton = QtWidgets.QPushButton(self.previous_versions_groupBox)
        self.open_pushButton.setObjectName("open_pushButton")
        self.horizontalLayout_5.addWidget(self.open_pushButton)
        self.reference_pushButton = QtWidgets.QPushButton(self.previous_versions_groupBox)
        self.reference_pushButton.setObjectName("reference_pushButton")
        self.horizontalLayout_5.addWidget(self.reference_pushButton)
        self.import_pushButton = QtWidgets.QPushButton(self.previous_versions_groupBox)
        self.import_pushButton.setObjectName("import_pushButton")
        self.horizontalLayout_5.addWidget(self.import_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(self.previous_versions_groupBox)
        self.close_pushButton.setStyleSheet("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_5.addWidget(self.close_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14.addWidget(self.previous_versions_groupBox)
        self.horizontalLayout_14.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout.addWidget(self.verticalWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.description_textEdit, self.export_as_pushButton)
        Dialog.setTabOrder(self.export_as_pushButton, self.save_as_pushButton)
        Dialog.setTabOrder(self.save_as_pushButton, self.previous_versions_tableWidget)
        Dialog.setTabOrder(self.previous_versions_tableWidget, self.open_pushButton)
        Dialog.setTabOrder(self.open_pushButton, self.reference_pushButton)
        Dialog.setTabOrder(self.reference_pushButton, self.import_pushButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Version Creator - Stalker", None, -1))
        self.logged_in_as_label.setText(QtWidgets.QApplication.translate("Dialog", "<b>Logged In As:</b>", None, -1))
        self.logged_in_user_label.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))
        self.logout_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Logout", None, -1))
        self.tasks_groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Tasks", None, -1))
        self.my_tasks_only_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Show my tasks only", None, -1))
        self.tasks_treeView.setToolTip(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p>Right Click:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To go to the <span style=\" font-weight:600;\">Dependent Tasks</span></li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To go to the <span style=\" font-weight:600;\">Dependee Tasks</span></li></ul><p><br/></p></body></html>", None, -1))
        self.recent_files_comboBox.setToolTip(QtWidgets.QApplication.translate("Dialog", "Recent Files", None, -1))
        self.clear_recent_files_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear", None, -1))
        self.find_from_path_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Find From Path", None, -1))
        self.find_from_path_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Find", None, -1))
        self.upload_thumbnail_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Upload", None, -1))
        self.clear_thumbnail_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear", None, -1))
        self.new_version_groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "New Version", None, -1))
        self.takes_label.setText(QtWidgets.QApplication.translate("Dialog", "Take", None, -1))
        self.repr_as_separate_takes_checkBox.setToolTip(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p>Check this to show <span style=\" font-weight:600;\">Representations</span> as separate takes if available</p></body></html>", None, -1))
        self.repr_as_separate_takes_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Show Repr.", None, -1))
        self.add_take_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "New Take", None, -1))
        self.description_label.setText(QtWidgets.QApplication.translate("Dialog", "Desc.", None, -1))
        self.description_textEdit.setHtml(QtWidgets.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>", None, -1))
        self.export_as_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Selection As", None, -1))
        self.save_as_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Save As", None, -1))
        self.publish_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Publish", None, -1))
        self.previous_versions_groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Previous Versions", None, -1))
        self.show_only_label.setText(QtWidgets.QApplication.translate("Dialog", "Show Only", None, -1))
        self.show_published_only_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Show Published Only", None, -1))
        self.previous_versions_tableWidget.setToolTip(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p>Right click to:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li><span style=\" font-weight:600;\">Copy Path</span></li><li><span style=\" font-weight:600;\">Browse Path</span></li><li><span style=\" font-weight:600;\">Change Description</span></li></ul><p>Double click to:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Open</span></li></ul></body></html>", None, -1))
        self.previous_versions_tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Version", None, -1))
        self.previous_versions_tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "User", None, -1))
        self.previous_versions_tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Dialog", "File Size", None, -1))
        self.previous_versions_tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Dialog", "Date", None, -1))
        self.previous_versions_tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Dialog", "Description", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Repr", None, -1))
        self.representations_comboBox.setToolTip(QtWidgets.QApplication.translate("Dialog", "Choose Representation (if supported by the environment)", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Refs", None, -1))
        self.ref_depth_comboBox.setToolTip(QtWidgets.QApplication.translate("Dialog", "Choose reference depth (if supported by environment)", None, -1))
        self.useNameSpace_checkBox.setToolTip(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p>Uncheck it if you are going to use <span style=\" font-weight:600;\">Alembic Cache</span>.</p></body></html>", None, -1))
        self.useNameSpace_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Use Namespace", None, -1))
        self.chose_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Choose", None, -1))
        self.checkUpdates_checkBox.setToolTip(QtWidgets.QApplication.translate("Dialog", "Disable update check (faster)", None, -1))
        self.checkUpdates_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Check Updates", None, -1))
        self.open_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Open", None, -1))
        self.reference_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Reference", None, -1))
        self.import_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Import", None, -1))
        self.close_pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Close", None, -1))

