"""Contains playblast related functions for Maya."""

import copy
import glob
import json
import pprint
import os
import shutil
import tempfile
from typing import Dict, List, Optional, Union
import pymel.core as pm

from stalker import File, LocalSession, Version
from stalker.db.session import DBSession

import timecode

from anima.dcc.maya import previs
from anima.dcc.maya.common import Maya, get_maya_main_window
from anima.utils import MediaManager, milliseconds_to_tc
from anima.utils.progress import ProgressManagerFactory


def perform_playblast(
    action: int = 0,
    resolution: int = 100,
    playblast_view_options: Optional[Dict] = None,
    upload_to_server: Optional[bool] = None,
    force_batch_mode: bool = False,
) -> Union[None, str]:
    """The patched version of the original perform playblast.

    Args:
        action (int): Passed directly to the Maya version of the playblast if
            the current scene is not related to a Stalker Version.
        resolution(int): An integer value one of 25, 50, 100 defining the
            playblast resolution as a percent fraction of the original scene
            resolution. Default value is 100. If given as None, the value or
            this argument will be asked to the user.
        playblast_view_options (Optional[Dict]): A dictionary containing the
            view options. ``auxiliary.get_default_playblast_view_options`` can
            be used to get one. If given as None, the value or this argument
            will be asked to the user.
        upload_to_server (Optional[bool]): A bool value to specify if the
            resultant video should be uploaded to the server or not. If given
            as None, the value or this argument will be asked to the user.
        force_batch_mode (bool): If True will force the playblast to be in
            batch mode.

    Returns:
        Union[None, str]: The playblast command generated by the original Maya
            playblast command.
    """
    # check if the current scene is a Stalker related version
    # if not call the default playblast
    # if it is call out ShotPlayblaster
    m = Maya()
    v = m.get_current_version()

    if not v:
        # call the original playblast
        return pm.mel.eval(f"performPlayblast_orig({action});")

    # do use playblaster
    extra_playblast_options = {"viewer": 0}

    # always use PNG as image format which now properly supports audio files
    extra_playblast_options["fmt"] = "image"
    extra_playblast_options["compression"] = "png"

    # ask resolution
    if resolution is None:
        resolution = ask_playblast_resolution()

    if resolution is None:
        return

    extra_playblast_options["percent"] = resolution

    # ask for playblast view options
    if playblast_view_options is None:
        playblast_view_options = ask_playblast_view_options()

    pb = Playblaster(
        playblast_view_options=playblast_view_options,
        force_batch_mode=force_batch_mode,
    )
    outputs = pb.playblast(extra_playblast_options=extra_playblast_options)

    if not outputs:
        return

    if upload_to_server is None:  # so no default options
        response = pm.confirmDialog(
            title="Upload To Server?",
            message="Upload To Server?",
            button=["Yes", "No"],
            defaultButton="No",
            cancelButton="No",
            dismissString="No",
        )
    else:
        response = "Yes" if upload_to_server else "No"

    if response == "Yes":
        for output in outputs:
            pb.upload_file(pb.version, output)


def ask_playblast_resolution() -> Union[None, int]:
    """Ask the user the playblast resolution.

    Returns:
        Union[None, int]: The resolution value.
    """
    # ask resolution
    response = pm.confirmDialog(
        title="Resolution?",
        message="Resolution?",
        button=["Default", "Full", "Half", "Quarter", "Cancel"],
        defaultButton="Default",
        cancelButton="Default",
        dismissString="Default",
    )
    if response == "Default":
        return 50
    elif response == "Full":
        return 100
    elif response == "Half":
        return 50
    elif response == "Quarter":
        return 25
    elif response == "Cancel":
        return None

    return 100


def get_default_playblast_view_options() -> Dict:
    """Return a copy of the default_playblast_View_options.

    Returns:
        Dict: The default playblast view options.
    """
    return copy.copy(Playblaster.default_view_options)


def ask_playblast_view_options() -> Dict:
    """Ask the user the playblast view options.

    It will store the last selected view options and if there are no previously
    selected view options it will use the defaults from the Playblaster

    Returns:
        Dict: The selected view options.
    """
    # storage
    user_playblast_view_options_storage = os.path.join(
        tempfile.gettempdir(), "playblast_view_options.json"
    )

    use_defaults = False
    if os.path.exists(user_playblast_view_options_storage):
        try:
            with open(user_playblast_view_options_storage, "r") as f:
                user_playblast_view_options = json.load(f)
        except ValueError:
            use_defaults = True
    else:
        use_defaults = True

    if use_defaults:
        user_playblast_view_options = get_default_playblast_view_options()

    # display the current options and ask the user to change them
    # sadly we need to use Qt to display a proper modal dialog
    from anima.ui.lib import QtCore, QtWidgets

    class PlayblastViewOptionsDialog(QtWidgets.QDialog):
        def __init__(self, options=None):
            parent = get_maya_main_window()
            super(PlayblastViewOptionsDialog, self).__init__(parent=parent)
            self.options = options
            self.checkers = []
            self._setup()

        def _setup(self) -> None:
            """Setup the dialog."""
            self.setWindowTitle("Playblast View Options")
            # self.resize(517, 545)
            vertical_layout = QtWidgets.QVBoxLayout(self)

            use_defaults_button = QtWidgets.QPushButton(self)
            use_defaults_button.setText("Use Defaults")
            vertical_layout.addWidget(use_defaults_button)

            horizontal_layout = QtWidgets.QHBoxLayout()
            vertical_layout.addLayout(horizontal_layout)

            current_vertical_layout = QtWidgets.QVBoxLayout()
            horizontal_layout.addLayout(current_vertical_layout)

            vertical_button_count = 10

            i = 0
            for k in sorted(self.options.keys()):
                v = self.options[k]
                i += 1
                if isinstance(v, bool):
                    checker = QtWidgets.QCheckBox(k, parent=self)
                    checker.setChecked(v)
                    current_vertical_layout.addWidget(checker)
                    self.checkers.append(checker)

                if i % vertical_button_count == 0:
                    # create a new vertical layout
                    current_vertical_layout = QtWidgets.QVBoxLayout()
                    horizontal_layout.addLayout(current_vertical_layout)

            # add a spacer to the last column layout
            spacer_item = QtWidgets.QSpacerItem(
                20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
            )
            current_vertical_layout.addItem(spacer_item)

            button_box = QtWidgets.QDialogButtonBox(self)
            button_box.setOrientation(QtCore.Qt.Horizontal)
            button_box.setStandardButtons(
                QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
            )
            vertical_layout.addWidget(button_box)
            vertical_layout.setStretch(2, 1)

            # Button box
            QtCore.QObject.connect(button_box, QtCore.SIGNAL("accepted()"), self.accept)
            QtCore.QObject.connect(button_box, QtCore.SIGNAL("rejected()"), self.reject)
            QtCore.QObject.connect(
                use_defaults_button,
                QtCore.SIGNAL("clicked()"),
                self.use_defaults_push_button_clicked,
            )

        def use_defaults_push_button_clicked(self) -> None:
            """Set the default values."""
            for checker in self.checkers:
                checker.setChecked(
                    Playblaster.default_view_options[str(checker.text())]
                )

        def get_playblast_options(self) -> Dict:
            """Return the current selected options.

            Returns:
                Dict: The current selected options.
            """
            playblast_options = {}
            for checker in self.checkers:
                playblast_options[str(checker.text())] = checker.isChecked()
            return playblast_options

    pb_view_options_dialog = PlayblastViewOptionsDialog(
        options=user_playblast_view_options
    )
    pb_view_options_dialog.exec_()

    user_playblast_view_options = pb_view_options_dialog.get_playblast_options()
    # write it down
    with open(user_playblast_view_options_storage, "w") as f:
        json.dump(user_playblast_view_options, f)

    return user_playblast_view_options


def perform_playblast_shot(shot_name: str) -> None:
    """Perform shot playblast

    This is written to replace the menu action in Camera Sequencer.

    Args:
        shot_name (str): Shot name
    """
    if not shot_name:
        return

    response = pm.confirmDialog(
        title="Perform Playblast?",
        message="Perform Playblast?",
        button=["Yes", "No"],
        defaultButton="No",
        cancelButton="No",
        dismissString="No",
    )
    if response == "No":
        return

    # ask resolution
    resolution = 100

    extra_playblast_options = {"viewer": 0, "percent": resolution}

    if " " in shot_name:
        # there are probably more than one shot
        shots = [pm.PyNode(s_name) for s_name in shot_name.split(" ")]
    else:
        shots = [pm.PyNode(shot_name)]

    pb = Playblaster()
    video_file_outputs = []
    for shot in shots:
        video_file_output = pb.playblast_shot(
            shot, extra_playblast_options=extra_playblast_options
        )
        video_file_outputs.append(video_file_output)

    response = pm.confirmDialog(
        title="Upload To Server?",
        message="Upload To Server?",
        button=["Yes", "No"],
        defaultButton="No",
        cancelButton="No",
        dismissString="No",
    )
    if response == "Yes":
        for video_file_output in video_file_outputs:
            pb.upload_file(pb.version, video_file_output)


class Playblaster(object):
    """Generate playblasts.

    If there are shots in the current scene then it generates playblasts for
    each of them and uploads it to the server
    """

    default_view_options = {
        "cameras": False,
        "clipGhosts": False,
        "cv": False,
        "deformers": False,
        "dimensions": False,
        "displayAppearance": "smoothShaded",  # Smooth shaded
        "displayLights": "default",  # default lighting
        "shadows": False,  # No Shadows
        # "udm": True,  # use default material
        "dynamics": True,
        "dynamicConstraints": False,
        "fluids": True,
        "follicles": False,
        "greasePencils": False,
        "grid": False,
        "handles": False,
        "hairSystems": False,
        "hulls": False,
        "ikHandles": False,
        "imagePlane": True,
        "joints": False,
        "lights": False,
        "locators": False,
        "manipulators": False,
        "motionTrails": False,
        "nCloths": True,
        "nParticles": True,
        "nRigids": False,
        "nurbsCurves": False,
        "nurbsSurfaces": False,
        "particleInstancers": True,
        "pivots": False,
        "planes": True,
        "pluginShapes": False,
        "pluginObjects": ("gpuCacheDisplayFilter", True),
        "polymeshes": True,
        "strokes": False,
        "subdivSurfaces": True,
        "textures": False,
    }

    cam_attribute_names = [
        "overscan",
        "filmFit",
        "displayFilmGate",
        "displayResolution",
        "displayGateMask",
        "displayFieldChart",
        "displaySafeAction",
        "displaySafeTitle",
        "displayFilmPivot",
        "displayFilmOrigin",
    ]

    hardware_rendering_globals_attr_names = [
        "ssaoEnable",
        "motionBlurEnable",
        "multiSampleEnable",
    ]

    global_playblast_options = {
        "fmt": "image",
        "forceOverwrite": 1,
        "clearCache": 1,
        "showOrnaments": 1,
        "percent": 100,
        "offScreen": 1,
        "viewer": 0,
        "compression": "png",
        "quality": 85,
        "sequenceTime": 1,
    }

    hud_name = "PlayblasterHUD"

    def __init__(self, playblast_view_options=None, force_batch_mode=False):
        self._playblast_view_options = None
        self.playblast_view_options = playblast_view_options
        self.batch_mode = force_batch_mode or pm.general.about(batch=1)

        self.logged_in_user = None
        if not self.batch_mode:
            local_session = LocalSession()
            self.logged_in_user = local_session.logged_in_user

            if not self.logged_in_user:
                raise RuntimeError("Please login first!")

        self.version = None
        self.m_env = Maya()
        self.version = self.m_env.get_current_version()

        self.user_view_options = {}
        self.reset_user_view_options_storage()

    def check_sequence_name(self) -> None:
        """Check sequence name and prompt user if not set (in UI mode)."""
        local_sequencers = [
            seq for seq in pm.ls(type="sequencer") if seq.referenceFile() is None
        ]
        if not local_sequencers:
            sequencer = pm.nt.Sequencer()
        else:
            sequencer = local_sequencers[0]

        try:
            sequence_name = sequencer.getAttr("sequence_name")
        except pm.MayaAttributeError:
            previs.Previs.add_sequence_name_attribute_to_sequencer(sequencer)
            sequence_name = sequencer.getAttr("sequence_name")

        if sequence_name != "" or self.batch_mode:
            return

        result = pm.promptDialog(
            title="Please enter a Sequence Name",
            message="Sequence Name:",
            button=["OK", "Cancel"],
            defaultButton="OK",
            cancelButton="Cancel",
            dismissString="Cancel",
        )

        if result == "OK":
            sequencer.setAttr("sequence_name", pm.promptDialog(query=True, text=True))

    def get_hud_data(self) -> str:
        """Return HUD data.

        Returns:
            str: The HUD data.
        """
        # try to get the shot from sequencer
        current_shot = pm.sequenceManager(q=1, currentShot=1)

        current_cam_name = "NoCameraFound"
        if current_shot:
            shot_name = pm.getAttr(f"{current_shot}.shotName")
            current_cam_name = pm.shot(current_shot, q=1, cc=1)
            if current_cam_name:
                current_cam = pm.PyNode(current_cam_name)
            else:
                # there is no camera in this shot
                # use the first camera in the scene
                # TODO: using the first camera is not a good idea
                current_cam = pm.ls(type=pm.nt.Camera)[0].getParent()
                current_cam_name = current_cam.name()
        else:
            # then try to get the shot name from the file name
            shot_name = os.path.split(pm.sceneName())[1].split("_")[0]
            # use the active panel camera
            current_cam = self.get_active_panel_camera()

            if current_cam is not None:
                current_cam_name = current_cam.name()

        if isinstance(current_cam, pm.nt.Transform):
            current_cam = current_cam.getShape()

        focal_length = 0

        if current_cam is not None:
            focal_length = current_cam.getAttr("focalLength")

        sequencers = pm.ls(type="sequencer")
        if sequencers:
            sequencer = sequencers[0]
            if not sequencer.hasAttr("sequence_name"):
                previs.Previs.add_sequence_name_attribute_to_sequencer(sequencer)
            if sequencer.getAttr("sequence_name") != "":
                shot_info = sequencer.getAttr("sequence_name")
            else:
                shot_info = "INVALID"
        else:
            shot_info = shot_name

        cf = int(pm.currentTime(q=1)) + 1

        frame_rate = 25
        maya_env = Maya()
        v = maya_env.get_current_version()
        if v:
            frame_rate = v.task.project.fps
        tc = timecode.Timecode(frame_rate, frames=cf)

        if current_shot:
            start_time = pm.shot(current_shot, q=1, st=1)
            end_time = pm.shot(current_shot, q=1, et=1)
        else:
            # no shot node use the current playback range
            start_time = pm.playbackOptions(q=1, min=1)
            end_time = pm.playbackOptions(q=1, max=1)

        cs_frame = int(cf - start_time)

        length = int(end_time - start_time) + 1

        if self.version:
            user_name = (
                self.version.updated_by.name if self.version.updated_by else "None"
            )
        else:
            # get the user name from the login info
            if self.logged_in_user:
                user_name = self.logged_in_user.name
            else:
                # ok try to use the filename
                user_name = pm.sceneName().split("_")[-1]

        hud_string = (
            "{} | {}:{}mm | tc:{} [{}] | Shot: {} | Length: {}/{}fr | [{}]".format(
                shot_info,
                current_cam_name.split(":")[-1],
                int(focal_length),
                tc,
                str(int(cf) - 1).zfill(4),
                shot_name.split(":")[-1],
                cs_frame,
                str(length).zfill(3),
                user_name,
            )
        )
        return hud_string

    def get_active_panel_camera(self) -> Union[None, pm.nt.Camera]:
        """Return the active view camera.

        Returns:
            Union[None, pm.nt.Camera]: The active view camera.
        """
        active_panel = self.get_active_panel()
        current_cam = None
        try:
            current_cam = pm.modelEditor(active_panel, q=1, cam=1)
        except pm.MayaNodeError as e:
            pass

        # really return the camera node and not the transform node
        if isinstance(current_cam, pm.nt.Transform):
            current_cam = current_cam.getShape()

        return current_cam

    def create_hud(self, hud_name: str) -> None:
        """Create HUD."""
        self.remove_hud(hud_name)

        try:
            # create our HUD
            pm.headsUpDisplay(
                hud_name,
                section=7,
                block=1,
                ao=1,
                blockSize="medium",
                labelFontSize="large",
                dfs="large",
                command=self.get_hud_data,
                atr=1,
            )
        except RuntimeError:
            # there is another HUD in that position remove it
            pm.headsUpDisplay(removePosition=(7, 1))
            self.create_hud(hud_name)

    def remove_hud(self, hud_name: Optional[str] = None) -> None:
        """Remove the HUD."""
        if hud_name and pm.headsUpDisplay(hud_name, q=1, ex=1):
            pm.headsUpDisplay(hud_name, rem=1)

    @classmethod
    def get_shot_cameras(cls) -> List[pm.nt.Camera]:
        """Return the shot cameras.

        Returns:
            List[pm.nt.Camera]: The shot cameras.
        """
        # store camera display options
        cameras = []
        for shot in pm.sequenceManager(listShots=1):
            camera_name = pm.shot(shot, q=1, cc=1)
            camera = pm.PyNode(camera_name)
            if isinstance(camera, pm.nt.Transform):
                camera = camera.getShape()
            cameras.append(camera)
        return cameras

    def get_selected_frame_range(self) -> List[int]:
        """Return the playback range.

        Returns:
            List[int]: The playback range.
        """
        start_time = int(pm.playbackOptions(q=1, ast=1))
        end_time = int(pm.playbackOptions(q=1, aet=1))

        if self.batch_mode:
            return [start_time, end_time]

        selected_start_time, selected_end_time = list(
            map(
                int,
                pm.timeControl(pm.melGlobals["$gPlayBackSlider"], q=1, rangeArray=True),
            )
        )

        if selected_end_time - selected_start_time > 1:
            # the selection is valid
            start_time = selected_start_time
            end_time = selected_end_time

        return [start_time, end_time]

    def is_frame_range_selected(self) -> bool:
        """Return true if a range in the time line is selected.

        Returns:
            bool: True if a range in the time line is selected.
        """
        if self.batch_mode:
            return False

        start, end = list(
            map(
                int,
                pm.timeControl(pm.melGlobals["$gPlayBackSlider"], q=1, rangeArray=True),
            )
        )
        return (end - start) > 1

    @classmethod
    def get_audio_node(cls) -> Union[None, pm.nt.Audio]:
        """Return the audio node from the time slider.

        Returns:
            Union[None, pm.nt.Audio]: The audio node.
        """
        audio_node_name = pm.timeControl(
            pm.melGlobals["$gPlayBackSlider"], q=1, sound=1
        )
        try:
            audio_node = pm.PyNode(audio_node_name)
        except pm.MayaNodeError:
            return
        return audio_node

    def reset_user_view_options_storage(self) -> None:
        """Reset the user view options storage."""
        self.user_view_options = {
            "view_options": {},
            "huds": {},
            "camera_flags": {},
            "hardware_rendering_globals": {},
        }

    def store_user_options(self) -> None:
        """Store user options."""
        # query active model panel
        active_panel = self.get_active_panel()

        # store show/hide display options for active panel
        self.reset_user_view_options_storage()

        for flag in self.default_view_options.keys():
            try:
                self.user_view_options["view_options"][flag] = pm.modelEditor(
                    active_panel, **{"q": 1, flag: True}
                )
            except TypeError:
                pass

        # store hud display options
        hud_names = pm.headsUpDisplay(lh=1)
        if hud_names:  # in batch mode there is no hud_names
            for hud_name in hud_names:
                self.user_view_options["huds"][hud_name] = pm.headsUpDisplay(
                    hud_name, q=1, vis=1
                )

        for camera in pm.ls(type="camera"):
            camera_name = camera.name()
            per_camera_attr_dict = {}
            for attr in self.cam_attribute_names:
                per_camera_attr_dict[attr] = camera.getAttr(attr)
            self.user_view_options["camera_flags"][camera_name] = per_camera_attr_dict

        hrg = pm.PyNode("hardwareRenderingGlobals")
        for attr in self.hardware_rendering_globals_attr_names:
            self.user_view_options["hardware_rendering_globals"][attr] = hrg.getAttr(
                attr
            )

    @property
    def playblast_view_options(self) -> Dict:
        """Return the playblast_view_options.

        Returns:
            Dict: The playblast_view_options.
        """
        return self._playblast_view_options

    @playblast_view_options.setter
    def playblast_view_options(self, playblast_view_options: Dict) -> None:
        """Set the playblast view options.

        Args:
            playblast_view_options (Dict): A dict for the desired options.
        """
        # use defaults if empty
        if not playblast_view_options:
            playblast_view_options = self.default_view_options

        self._playblast_view_options = playblast_view_options

    def set_view_options(self) -> None:
        """Set view options for playblast."""
        active_panel = self.get_active_panel()
        pm.modelEditor(active_panel, e=1, **self.playblast_view_options)

        # turn all hud displays off
        hud_flags = pm.headsUpDisplay(lh=1)
        if hud_flags:  # in batch mode there is node headsUpDisplay
            for flag in hud_flags:
                pm.headsUpDisplay(flag, e=1, vis=0)

        # set camera options for playblast
        for camera in pm.ls(type="camera"):
            try:
                camera.setAttr("overscan", 1)
            except RuntimeError:
                pass

            try:
                camera.setAttr("filmFit", 1)
            except RuntimeError:
                pass

            try:
                camera.setAttr("displayFilmGate", 1)
            except RuntimeError:
                pass

            try:
                camera.setAttr("displayResolution", 0)
            except RuntimeError:
                pass

        # pm.mel.eval('displayStyle("-ss")')

        # set hardwareRenderingGlobals attributes for playblast
        hrg = pm.PyNode("hardwareRenderingGlobals")
        hrg.setAttr("ssaoEnable", False)
        hrg.setAttr("multiSampleEnable", True)

    def restore_user_options(self) -> None:
        """Restore user options."""
        active_panel = self.get_active_panel()
        for flag, value in self.user_view_options["view_options"].items():
            try:
                pm.modelEditor(active_panel, **{"e": 1, flag: value})
            except TypeError:
                pass

        # reassign original hud display options
        for hud, value in self.user_view_options["huds"].items():
            if pm.headsUpDisplay(hud, q=1, ex=1):
                pm.headsUpDisplay(hud, e=1, vis=value)

        # reassign original camera options
        for camera in pm.ls(type="camera"):
            camera_name = camera.name()

            try:
                camera_flags = self.user_view_options["camera_flags"][camera_name]
            except KeyError:
                continue

            for attr, value in camera_flags.items():
                try:
                    camera.setAttr(attr, value)
                except RuntimeError:
                    pass

        # re-set original hardware rendering globals
        hrg = pm.PyNode("hardwareRenderingGlobals")
        for attr in self.hardware_rendering_globals_attr_names:
            value = self.user_view_options["hardware_rendering_globals"][attr]
            hrg.setAttr(attr, value)

        self.remove_hud(self.hud_name)

    @classmethod
    def get_active_panel(cls) -> pm.nt.ModelPanel:
        """Return the active model panel.

        Returns:
            pm.nt.ModelPanel: The active model panel.
        """
        active_panel = None
        panel_list = pm.getPanel(type="modelPanel")
        for panel in panel_list:
            if pm.modelEditor(panel, q=1, av=1):
                active_panel = panel
                break

        return active_panel

    def playblast(self, extra_playblast_options: Optional[Dict] = None) -> List[str]:
        """Do a scene playblast.

        Decide what kind of playblast it needs to do.

        extra_playblast_options (Optional[Dict]): An optional dictionary for
            extra playblast options.

        Returns:
            List[str]: The resultant movie file or files.
        """
        # if there is a shot in the scene do a shot playblast
        shots = pm.ls(type="shot")
        if not extra_playblast_options:
            extra_playblast_options = {}

        # if a time range is selected do a simple playblast
        # the following will return ``False`` in batch mode
        start, end = self.get_selected_frame_range()
        if len(shots) and not self.is_frame_range_selected():
            if not self.batch_mode:
                response = pm.confirmDialog(
                    title="Which Camera?",
                    message="Which Camera?",
                    button=["Current", "Shot Camera", "Cancel"],
                    defaultButton="Shot Camera",
                    cancelButton="Cancel",
                    dismissString="Cancel",
                )
            else:
                response = "Shot Camera"

            if response == "Current":
                extra_playblast_options["sequenceTime"] = 0
            elif response == "Shot Camera":
                extra_playblast_options["sequenceTime"] = 1
            else:
                return []
            return self.playblast_all_shots(extra_playblast_options)
        else:
            extra_playblast_options["startTime"] = start
            extra_playblast_options["endTime"] = end
            return self.playblast_simple(extra_playblast_options)

    def playblast_simple(
        self, extra_playblast_options: Optional[Dict] = None
    ) -> List[str]:
        """Do a simple playblast.

        Args:
            extra_playblast_options (Optional[Dict]): An optional dictionary
                for extra playblast options.

        Returns:
            List[str]: A list of  strings showing the path of the resultant
                movie file or files.
        """
        playblast_options = copy.copy(self.global_playblast_options)
        playblast_options["sequenceTime"] = False
        playblast_options["percent"] = 100

        if extra_playblast_options:
            playblast_options.update(extra_playblast_options)

        # find some audio
        audio_node = self.get_audio_node()
        if audio_node:
            playblast_options["sound"] = audio_node
            playblast_options["useTraxSounds"] = False
        else:
            playblast_options["useTraxSounds"] = True

        # width height
        if "wh" not in playblast_options:
            # get project resolution
            # use half HD by default
            width = 1920
            height = 1080
            if self.version:
                project = self.version.task.project
                # get the resolution
                imf = project.image_format
                width = int(imf.width)
                height = int(imf.height)

            playblast_options["wh"] = (width, height)

        # output path
        if "filename" not in playblast_options:
            if self.version:
                # use version.base_name plus the camera name
                current_camera = self.get_active_panel_camera()
                current_camera_name = "Camera"
                if current_camera is not None:
                    # use the transform
                    current_camera_name = (
                        current_camera.getParent().name().split(":")[-1]
                    )
                filename = "{}_{}".format(
                    os.path.splitext(self.version.filename)[0],
                    current_camera_name,
                )  # node name
            else:
                # use the current scene name
                filename = os.path.splitext(os.path.basename(pm.sceneName()))[0]
            # also render to the same folder with the file
            output_dir = os.path.join(os.path.dirname(pm.sceneName()), "temp")

            playblast_options["filename"] = os.path.join(output_dir, filename).replace(
                "\\", "/"
            )

        maya_dcc = Maya()
        fps = maya_dcc.get_fps()

        result = []
        try:
            self.store_user_options()
            self.set_view_options()
            self.create_hud(self.hud_name)
            pprint.pprint(playblast_options)

            # update all cameras in the scene to have correct film back
            for cam in pm.ls(type="camera"):
                try:
                    cam.verticalFilmAperture.set(
                        cam.horizontalFilmAperture.get()
                        * float(playblast_options["wh"][1])
                        / float(playblast_options["wh"][0])
                    )
                except (AttributeError, RuntimeError) as e:
                    pass

            result = [
                {
                    "video": pm.playblast(**playblast_options),
                    "audio": {
                        "node": audio_node,
                        "offset": (
                            playblast_options.get("startTime", 0)
                            - audio_node.offset.get()
                            if audio_node
                            else 0
                        ),
                        "duration": (
                            playblast_options.get("endTime", 0)
                            - playblast_options.get("startTime", 0)
                            + 1
                        ),
                    },
                }
            ]
        finally:
            self.restore_user_options()

        video = self.convert_image_sequence_to_video(
            result, delete_source_sequence=True
        )
        return video

    @classmethod
    def convert_image_sequence_to_video(
        cls,
        data: Dict,
        delete_source_sequence: bool = False,
    ) -> List[str]:
        """Convert image sequence to video.

        Args:
            data [Dict]: A dictionary containing audio and video information in
                the following format:

                {
                    'video': 'video_path',
                    'audio': {
                        'node': audio_node_path,
                        'offset': in frames,
                        'duration': in frames
                    }
                }

            delete_source_sequence (bool): If True, this option will let the
                function to delete the source image sequence.

        Returns:
            List[str]: A list of strings showing the path of the resultant
                movie file or files.
        """
        frame_rate = 25
        maya_dcc = Maya()
        v = maya_dcc.get_current_version()
        if v:
            frame_rate = v.task.project.fps

        # convert image sequences to h264
        new_result = []
        original_image_sequence_path = ""
        for output in data:
            # convert each output to a mp4 if the output is a frame
            # sequence
            video_file_path = output
            audio_data = None
            if isinstance(output, dict):
                # this is possibly a more complex output that includes audio
                video_file_path = output.get("video")
                audio_data = output.get("audio")

            original_image_sequence_path = video_file_path
            if video_file_path and "#" in video_file_path:
                # convert to mp4

                # add start_number option
                temp_str = video_file_path.replace("#", "*")
                sequence = sorted(glob.glob(temp_str))
                options = dict()
                if sequence:
                    # Ep002_004_0210_v007.mov.####.png
                    # fix start number for {:04d} to {:05d} passage (eg. 9900 to 10010)
                    smallest_start_number = 1e10
                    for file_in_seq in sequence:
                        filename = os.path.basename(file_in_seq)
                        filename = filename.replace(".mov", "")
                        start_number = int(filename.split(".")[1])
                        if start_number < smallest_start_number:
                            smallest_start_number = start_number

                    options["start_number"] = smallest_start_number

                # use the correct frame rate
                options["framerate"] = frame_rate
                options["r"] = frame_rate

                # first convert the #'s to {:03d} format
                temp_str = video_file_path.replace("#", "")
                hash_count = len(video_file_path) - len(temp_str)
                splits = video_file_path.split("#")
                video_file_path = "{}{}{}".format(
                    splits[0],
                    "{{:0{hash_count}d}}".format(hash_count=hash_count),
                    splits[-1],
                )
                video_file_path_h264 = splits[0].replace(".mov.", ".")

                # check audio output
                if audio_data:
                    audio_node = audio_data.get("node")
                    if audio_node:
                        audio_file_path = os.path.expandvars(audio_node.filename.get())
                        # audio offset should be subtracted from the current playblast range
                        # and should be converted to a TimeCode
                        audio_offset = audio_data.get("offset", 0)
                        audio_duration = audio_data.get("duration", 0)

                        options["i"] = [
                            os.path.normpath(video_file_path),
                            os.path.normpath(audio_file_path),
                        ]
                        options["map"] = ["0:0", "1:0"]

                        audio_offset_in_millie_seconds = int(
                            audio_offset * 1000 / frame_rate
                        )
                        duration_in_millie_seconds = int(
                            audio_duration * 1000 / frame_rate
                        )

                        options["ss"] = [
                            None,
                            milliseconds_to_tc(abs(audio_offset_in_millie_seconds)),
                        ]
                        options["to"] = [
                            None,
                            milliseconds_to_tc(
                                abs(audio_offset_in_millie_seconds)
                                + duration_in_millie_seconds
                            ),
                        ]

                mm = MediaManager()
                video_file_path = mm.convert_to_h264(
                    video_file_path, video_file_path_h264, options=options
                )

            new_result.append(video_file_path)

        # delete all the temp files
        if delete_source_sequence and "#" in original_image_sequence_path:
            try:
                video_file_pattern = original_image_sequence_path.replace("#", "*")
                for filename in glob.glob(video_file_pattern):
                    os.remove(filename)
            except (OSError, AttributeError):
                pass

        return new_result

    def playblast_shot(
        self, shot: pm.nt.Shot, extra_playblast_options: Optional[Dict] = None
    ) -> List[str]:
        """Do the real playblast.

        Args:
            shot (pm.nt.Shot): The shot node.
            extra_playblast_options (Optional[Dict]): An optional dictionary
                for extra playblast options.

        Returns:
            List[str]: A list of strings showing the path of the resultant
                movie file or files.
        """
        shot_playblast_options = copy.copy(self.global_playblast_options)

        shot_playblast_options.update({"sequenceTime": 1})
        if extra_playblast_options:
            shot_playblast_options.update(extra_playblast_options)

        # deselect all
        pm.select(cl=1)

        self.check_sequence_name()

        if "wh" not in shot_playblast_options:
            # get project resolution
            # use half HD by default
            width = 1920
            height = 1080
            if self.version:
                project = self.version.task.project
                # get the resolution
                imf = project.image_format
                width = int(imf.width)
                height = int(imf.height)

            shot_playblast_options["wh"] = (width, height)

        try:
            self.store_user_options()
            self.set_view_options()
            self.create_hud(self.hud_name)

            # create video playblast
            temp_video_file_full_path = shot.playblast(options=shot_playblast_options)
        finally:
            self.restore_user_options()

        return temp_video_file_full_path

    def playblast_all_shots(
        self, extra_playblast_options: Optional[Dict] = None
    ) -> List[str]:
        """Playblast all shots.

        Args:
            extra_playblast_options (Optional[Dict]): An optional dictionary
                for extra playblast options.

        Returns:
            List[str]: A list of strings showing the path of the resultant
                movie file or files.
        """
        shots = pm.ls(type="shot")
        if len(shots) <= 0:
            raise RuntimeError("There are no Shots in your Camera Sequencer.")

        pdm = ProgressManagerFactory.get_progress_manager()
        pdm.end_progress()

        caller = pdm.register(len(shots), "Generating Playblasts...")

        generic_playblast_options = {}
        if extra_playblast_options:
            generic_playblast_options.update(extra_playblast_options)

        # if the time range is selected from the time line
        # just use this range
        range_start, range_end = self.get_selected_frame_range()
        generic_playblast_options["startTime"] = range_start
        generic_playblast_options["endTime"] = range_end

        # check audio
        audio_node = self.get_audio_node()
        if audio_node:
            generic_playblast_options.update(
                {"useTraxSounds": False, "sound": audio_node}
            )
        else:
            generic_playblast_options["useTraxSounds"] = True

        temp_video_file_full_paths = []
        for shot in shots:
            per_shot_playblast_options = copy.copy(generic_playblast_options)

            shot_start_frame = shot.startFrame.get()
            shot_end_frame = shot.endFrame.get()
            per_shot_playblast_options["startTime"] = shot_start_frame
            per_shot_playblast_options["endTime"] = shot_end_frame

            if self.is_frame_range_selected():
                # skip this shot if the selected playback range do not
                # coincide with this shot range
                if (
                    range_start > shot_start_frame and range_start > shot_end_frame
                ) or (range_end < shot_start_frame and range_end < shot_end_frame):
                    caller.step()
                    continue

            temp_video_file_full_path = self.playblast_shot(
                shot, per_shot_playblast_options
            )
            temp_video_file_full_paths.append(
                {
                    "video": temp_video_file_full_path[0],
                    "audio": {
                        "node": audio_node,
                        "offset": (
                            audio_node.offset.get() - shot_start_frame
                            if audio_node
                            else 0
                        ),
                        "duration": shot_end_frame - shot_start_frame + 1,
                    },
                }
            )

            caller.step()

        return self.convert_image_sequence_to_video(
            temp_video_file_full_paths, delete_source_sequence=True
        )

    @classmethod
    def upload_files(
        cls, version: Version, video_file_full_paths: List[str]
    ) -> List[str]:
        """Bulk upload files to the given Version instance.

        Args:
            version: :class:`~stalker.Version` instance to upload the files to.
            video_file_full_paths (List[str]): List of file paths.

        Returns:
            List[str]: List of uploaded file paths.
        """
        pdm = ProgressManagerFactory.get_progress_manager()
        pdm.end_progress()

        files = []
        # register a new caller
        caller = pdm.register(len(video_file_full_paths), "Uploading Playblasts...")
        for file_full_path in video_file_full_paths:
            # upload output to server
            uploaded_file_full_path = cls.upload_file(
                version=version,
                file_full_path=file_full_path,
            )

            files.append(uploaded_file_full_path)
            caller.step()

        return files

    @classmethod
    def upload_file(cls, version: Version, file_full_path: str) -> str:
        """Upload the given file as a file for the given Version.

        Also generate a thumbnail and a web version if it is a movie file.

        Args:
            version (Version): The :class:`~stalker.Version` instance to upload
                the files to.
            file_full_path (str): The path of the media file.

        Returns:
            str: The uploaded file path.
        """
        if not isinstance(version, Version):
            raise RuntimeError(
                "version should be a stalker version instance, "
                f"not {version.__class__.__name__}: '{version}'"
            )

        hires_extension = ".mp4"
        webres_extension = ".webm"
        thumbnail_extension = ".png"

        if not os.path.exists(file_full_path):
            raise RuntimeError(f"File does not exits: {file_full_path}")

        file_name = os.path.basename(file_full_path)

        hires_file_name = "{}{}".format(
            os.path.splitext(file_name)[0],
            hires_extension,
        )

        webres_file_name = "{}{}".format(
            os.path.splitext(file_name)[0],
            webres_extension,
        )

        thumbnail_file_name = "{}{}".format(
            os.path.splitext(file_name)[0],
            thumbnail_extension,
        )

        task = version.task

        hires_path = os.path.join(
            task.absolute_path, "Outputs", "Stalker_Pyramid", hires_file_name
        )
        webres_path = os.path.join(
            task.absolute_path,
            "Outputs",
            "Stalker_Pyramid",
            "ForWeb",
            webres_file_name,
        )
        thumbnail_path = os.path.join(
            task.absolute_path,
            "Outputs",
            "Stalker_Pyramid",
            "Thumbnail",
            thumbnail_file_name,
        )

        # create folders
        os.makedirs(os.path.dirname(hires_path), exist_ok=True)
        os.makedirs(os.path.dirname(webres_path), exist_ok=True)
        os.makedirs(os.path.dirname(thumbnail_path), exist_ok=True)
        shutil.copy(file_full_path, hires_path)

        # generate the web version
        m = MediaManager()
        temp_web_version_full_path = m.generate_media_for_web(file_full_path)

        try:
            shutil.copy(temp_web_version_full_path, webres_path)
        except IOError:
            pass

        temp_thumbnail_full_path = m.generate_thumbnail(file_full_path)
        try:
            # also upload thumbnail
            shutil.copy(temp_thumbnail_full_path, thumbnail_path)
        except IOError:
            pass

        project = task.project
        repo = project.repository

        # try to find a file with the same name
        # assigned to the version as a file
        found = None
        hires_os_independent_path = repo.to_os_independent_path(hires_path)
        for file in version.files:
            if file.full_path == hires_os_independent_path:
                found = True
                break

        # if we found a file with the same name as the uploaded file,
        # just overwrite it.
        if not found:
            l_hires = File(
                full_path=repo.to_os_independent_path(hires_path),
                original_filename=hires_file_name,
            )

            l_for_web = File(
                full_path=repo.to_os_independent_path(webres_path),
                original_filename=hires_file_name,
            )

            l_hires.thumbnail = l_for_web
            version.files.append(l_hires)

            l_thumb = File(
                full_path=repo.to_os_independent_path(thumbnail_path),
                original_filename=hires_file_name,
            )
            l_for_web.thumbnail = l_thumb

            DBSession.add_all([l_hires, l_for_web, l_thumb])
            DBSession.commit()

        return hires_path
